GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYwODEyMTQ4MSwiZXhwIjoxNjA4MTIxNjYxfQ.Vmz_fzeNsAvqxVgStd0TBT-XZBn1HN5N7HW-T_73xeY

# DELETE http://localhost:4000/logout
# Content-Type: application/json

# {
#   "token": ""
# }

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUnlhbiIsImlhdCI6MTYwODEyMTQ2NX0.QBEOIL9eWkTETxKjCA_hxFlm4tjbJrknBkY1RYbDOY0"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{ "username": "Ryan" }