GET http://localhost:5000/api/v1/products HTTP/1.1

###
GET http://localhost:5000/api/v1/products/1 HTTP/1.1

###
POST http://localhost:5000/api/v1/products HTTP/1.1

###
PUT http://localhost:5000/api/v1/products/2 HTTP/1.1

###
DELETE http://localhost:5000/api/v1/products/3 HTTP/1.1